### ISSUE TITLE
Example usage

### ISSUE THREAD

**Issue by RogerHardiman** [heksesang/bmff#1]
Hi
Do you have any examples of using the buff library.
My target application is to take NALs from a H264 encoder and write them to a .MP4 file but any examples would be great to get me started with the library.

Thanks
Roger

**Comment by heksesang** [comment]
You'll need to look up the MPEG-4 spec and figure out what exact boxes you need. Then construct a BaseMedia object, add the boxes you need, then use SaveTo to write the data to file:

```
var baseMedia = new BaseMedia();
...
baseMedia.Children.Add(new MovieDataBox(source));
...
baseMedia.SaveTo(fs);
```

The library doesn't support parsing H.264 data yet, only the container format, so you'll have to construct the data for the Movie Data Box yourself.

Without knowing how your NALs are encapsulated, it's hard to give any more advice.
